### ISSUE TITLE
initiate predict earlier, before all isolate data is downloaded

### ISSUE THREAD

**Issue by mahafarhat** [farhat-lab/gentb-site#158] opened 2019-06-17 15:39 UTC
I am testing a large number of predict jobs submitted simultaneously. I find that currently all isolate fastq data need to be downloaded before any job is submitted to compute. Is it possible to avoid this delay as it can take 5-10minutes or longer for a large number of strains/fastq files to download.

**Comment by mahafarhat** [comment] 2019-06-17 16:00
Also I submitted 33 jobs simultaneously, and in the first 30min since submission only 12 jobs were running. The remaining 21 were still pending on o2 and haven't even commenced processing.

**Comment by mahafarhat** [comment] 2019-06-17 16:01
@Davey-Hughes adding you here in case you have any insight on launching jobs on orchestra before download is complete and if you've investigated the length of time a jobs is pending on o2. Perhaps we have to have a discussion with O2 on the job priority from gentb

**Comment by Davey-Hughes** [comment] 2019-06-17 17:30
I think it should be possible depending on how @doctormo implemented the download interface. If some files are ready, it should be possible to start processing them as soon as possible. The question here is what to do if some files fail to download properly, and perhaps they should fail individually and not affect the entire batch job. It would be beneficial then if, for a given batch job, users could re-upload failed files so they can keep their datasets organized.

In terms of pending jobs on O2, I know that there are different servers for "priority" jobs and by default gentb doesn't use them. It would be a good option to add, though it shouldn't be exposed directly to someone submitting the files, since I think the different categories of slurm servers are kind of an honor system for the people who have access to submitting jobs and what their importance is. The priority could definitely be per-user, and could also take into account the batch size or other factors.

Also, I think in testing some programs in the pipeline I built had their memory requirements bumped up, which can also slow down job submission both because gentb is taking up more resources and also because asking for more resources on a busy server will take longer to free up. I'm traveling for the next ~2 weeks, but I can see about doing an investigation on what the correlation is between input file size and required processing memory for each step in the pipeline. Then instead of each step in the pipeline always asking for say, 5 gigabytes, you could specify a range somehow. That way maybe most pipeline programs will only ask for 1 gigabyte, but occasionally a pipeline program will be able to ask for more.

**Comment by Davey-Hughes** [comment] 2019-06-17 17:39
@doctormo On a more general but related issue, what would you think about the gentb being able to pass environment variables to pipeline programs? I was thinking that in many cases we already have to wrap the functionality of a pipeline program into a batch or python script, passing some custom environment variables that describe some internal gentb/chore reasoning would be helpful. In the case of jobs being scheduled too slowly, perhaps the number of threads could be decided by gentb based on O2's load, and then the script could read these variables and adjust the actual commands accordingly. I think a system like this would be the easiest way to extend functionality to the pipeline programs, because increasing the complexity of the pipeline program's expressions makes it harder to use.

To this end, maybe gentb could continue supporting it's current way to write pipeline programs, but could also support at least previewing (aka read-only viewing) of a wrapper script. That way it's not necessary to write wrapper scripts, but since I expect it to become more common if more features are added that wrapper scripts can take advantage of, it would be nice when reviewing pipelines to just be able to read those scripts from the web interface.

**Comment by mahafarhat** [comment] 2019-06-17 18:13
Thanks @Davey-Hughes related to this the batch of 33 jobs has now completed processing. One of the jobs failed and no output for any is displayed: https://gentb.hms.harvard.edu/predict/a944ea401416a070a1f6431858efe0a8/

@doctormo Let me know if these three issues are indeed connected as they appear to be to me, or if they are separate and I will repost them as new issues

**Comment by Davey-Hughes** [comment] 2019-06-17 18:20
@mahafarhat when you click on the "Processing tab", scroll to the right, and click on the "enhancer" job that failed, the issue says:

`Traceback (most recent call last): File "/n/groups/gentb_www/bin/varMatchUnk.py", line 482, in <module> var = m[j].group() TypeError: '_sre.SRE_Match' object has no attribute '__getitem__'`

Seems like a small bug in one of the logical pathways in varMatchUnk.py that only this particular strain tested. '__getitem__' is when square brackets [] are used to index into an object, which isn't supported by an SRE_Match object (aka the result of a re.match() call). Should be a really easy fix. Whoever wrote varMatchUnk.py should be able to fix it in 5 mins.

**Comment by mahafarhat** [comment] 2019-06-17 18:46
Thanks @Davey-Hughes I'm trying to fix that small bug, but I was commenting on why none of the results for the other jobs/strains that ran without any errors are not provided to the user.

**Comment by doctormo** [comment] 2019-06-18 16:19
The first element is that they should be separate issues. But maybe the issue is fixed in the script itself?

Scheduling is only fixable on the hms IT side of things. They've got a priority system and it'd be worth finding out if we need tweaking for our gentb user.

Environment variables could be used, although it'd be a good thing to codify the settings we want to offer like we have with the memory and cpu.

**Comment by mahafarhat** [comment] 2019-06-18 20:36
@doctormo We should launch the jobs as soon as download is completed for that specific isolate not for the entire batch, at the moment its the latter.

We also need to display the results for the successfully processed isolates, even if a subset fails.

**Comment by doctormo** [comment] 2019-06-18 20:58
Results for successful batches should already be automatic.

For submitting jobs as soon as ready, I'll need to ponder over the code some before I can make a call on how much work it is. It could be simpler now the scripts for kicking off jobs are more robust.

**Closed** 2019-08-19 12:17 UTC
